In [1]:
!pip install faiss-cpu
!pip install sentence-transformers

In [2]:
import faiss
import numpy as np
import pandas as pd
from sentence_transformers import SentenceTransformer

/usr/local/lib/python3.10/dist-packages/sentence_transformers/cross_encoder/CrossEncoder.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange


In [3]:
df = pd.read_csv("sample_text.csv")
df

text category
0      Meditation and yoga can improve mental health   Health
1  Fruits, whole grains and vegetables helps cont...   Health
2  These are the latest fashion trends for this week  Fashion
3  Vibrant color jeans for male are becoming a trend  Fashion
4                 The concert starts at 7 PM tonight    Event
5  Navaratri dandiya program at Expo center in Mu...    Event
6  Exciting vacation destinations for your next trip   Travel
7  Maldives and Srilanka are gaining popularity i...   Travel

In [4]:
encoder = SentenceTransformer('all-mpnet-base-v2')

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


In [5]:
vector = encoder.encode(df['text'])
vector.shape

(8, 768)

In [6]:
dim = vector.shape[1]
dim

768

In [7]:
index = faiss.IndexFlatL2(dim)

In [8]:
index.add(vector)

In [9]:
index

<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x7c4676c07300> >

In [10]:
search_query = 'My next trip is going to be to Leh & Ladakh'
vec = encoder.encode(search_query)
vec

array([-2.39789430e-02,  2.44995928e-04, -2.51341593e-02, -1.82206482e-02,
       -4.68228158e-04, -1.74971744e-02,  1.42442696e-02,  1.54627478e-02,
        7.32305273e-02, -4.98655736e-02, -6.82857912e-03, -1.69740468e-02,
       -2.03561857e-02, -1.72068197e-02,  1.99198201e-02, -5.57453744e-02,
        1.41915809e-02, -9.70337391e-02, -7.99826533e-02, -2.76857410e-02,
       -4.97103482e-02, -4.07273956e-02, -3.57011892e-02, -1.82504673e-02,
        8.28966051e-02, -2.12566406e-02, -5.15110008e-02,  4.33461070e-02,
        6.51717409e-02, -5.10953516e-02, -4.77036834e-02, -2.97795031e-02,
        3.79048884e-02, -4.75510918e-02,  1.43898671e-06,  1.83198100e-03,
        8.21910566e-04, -2.83194110e-02,  1.29533550e-02, -3.99351791e-02,
        4.18915004e-02, -6.31404966e-02, -4.27037524e-03, -8.46227165e-03,
        1.47646023e-02, -4.68186252e-02,  4.16177139e-02,  1.24319652e-02,
       -1.96804409e-03,  6.72261566e-02,  6.60225144e-03,  2.54433369e-03,
       -3.81626599e-02,  

In [11]:
vec.shape

(768,)

In [12]:
svec = np.array(vec).reshape(1,-1)
svec

array([[-2.39789430e-02,  2.44995928e-04, -2.51341593e-02,
        -1.82206482e-02, -4.68228158e-04, -1.74971744e-02,
         1.42442696e-02,  1.54627478e-02,  7.32305273e-02,
        -4.98655736e-02, -6.82857912e-03, -1.69740468e-02,
        -2.03561857e-02, -1.72068197e-02,  1.99198201e-02,
        -5.57453744e-02,  1.41915809e-02, -9.70337391e-02,
        -7.99826533e-02, -2.76857410e-02, -4.97103482e-02,
        -4.07273956e-02, -3.57011892e-02, -1.82504673e-02,
         8.28966051e-02, -2.12566406e-02, -5.15110008e-02,
         4.33461070e-02,  6.51717409e-02, -5.10953516e-02,
        -4.77036834e-02, -2.97795031e-02,  3.79048884e-02,
        -4.75510918e-02,  1.43898671e-06,  1.83198100e-03,
         8.21910566e-04, -2.83194110e-02,  1.29533550e-02,
        -3.99351791e-02,  4.18915004e-02, -6.31404966e-02,
        -4.27037524e-03, -8.46227165e-03,  1.47646023e-02,
        -4.68186252e-02,  4.16177139e-02,  1.24319652e-02,
        -1.96804409e-03,  6.72261566e-02,  6.60225144e-0

In [13]:
svec.shape

(1, 768)

In [14]:
distances, I = index.search(svec, k = 2)

In [15]:
distances

array([[1.1574962, 1.2813841]], dtype=float32)

In [16]:
I

array([[6, 7]])

In [17]:
row_indices = I.tolist()[0]

In [18]:
df.loc[row_indices]

text category
6  Exciting vacation destinations for your next trip   Travel
7  Maldives and Srilanka are gaining popularity i...   Travel